sources:
  - sources/build/LXGWWenKaiMonoTC-Bold.designspace
  - sources/build/LXGWWenKaiMonoTC-Light.designspace
  - sources/build/LXGWWenKaiMonoTC-Regular.designspace
  - sources/build/LXGWWenKaiTC-Bold.designspace
  - sources/build/LXGWWenKaiTC-Light.designspace
  - sources/build/LXGWWenKaiTC-Regular.designspace
removeOutlineOverlaps: False
buildOTF: False
buildTTF: True
buildWebfont: False
autohintTTF: False
