sources:
  - build/LXGWWenKaiMonoTC-Bold.ufo
  - build/LXGWWenKaiMonoTC-Light.ufo
  - build/LXGWWenKaiMonoTC-Regular.ufo
  - build/LXGWWenKaiTC-Bold.ufo
  - build/LXGWWenKaiTC-Light.ufo
  - build/LXGWWenKaiTC-Regular.ufo
removeOutlineOverlaps: False
buildOTF: False
buildTTF: True
buildWebfont: False
autohintTTF: False
version: "1.330"
